spring:
  profiles:
    active: dev

---
#开发环境配置
spring:
  profiles: dev

server:
  port: 8080


---
#测试环境配置
spring:
  profiles: stg

server:
  port: 8081

---
#生产环境配置
spring:
  profiles: pro

server:
  port: 80

---

mybatis-plus:
    #mybatis对应的映射文件路径
    mapper-locations: classpath*:mapper/*/*Mapper.xml
    type-aliases-package: com.yunhe.*.entity

spring:
  #thymeleaf:
  thymeleaf:
    #不设置静态页面缓存
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html
    #配置redis
  redis:
    host: 47.106.37.123
    port: 6379
